gemini-hlsw/clue

core/shared/src/main/scala/clue/ApolloStreamingClient.scala, model/shared/src/main/scala/clue/model/StreamingMessage.scala, model/shared/src/main/scala/clue/model/json/package.scala, model/shared/src/test/scala/clue/model/arb/ArbFromServer.scala
According to the unofficial spec a `Data` message can contain `errors`: https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_data.
Here we implement that, and process the errors on the client.
=> Allow errors on Data streaming message.

macros/src/main/scala/clue/macros/GraphQL.scala, macros/src/main/scala/clue/macros/Macro.scala, macros/src/test/scala/clue/macros/MacroTest.scala, model/shared/src/main/scala/clue/model/StreamingMessage.scala
This allows client code to specify parent types for generated classes.
For example:
``` scala
trait Person {
val id: String
val name: Option[String]
}
@GraphQL(debug = false)
object SumQuery extends GraphQLOperation[StarWars] {
val document = """
query ($charId: ID!) {
character(id: $charId) {
id
name
}
"""
object Data {
trait Character extends Person
}
}
```
will generate:
``` scala
object SumQuery extends GraphQLOperation[StarWars] {
...
case class Character(id: String, name: Option[String]) extends Person
...
}
```
=> Specify synthetic class parents.

core/shared/src/main/scala/clue/ApolloStreamingClient.scala, model/shared/src/main/scala/clue/model/json/package.scala
* When a `Data` message decoding failed, the decoder attempted other types. This resulted in the reason for `Data` failing being lost.
* Some servers send a `Complete` message after `Stop` is sent, and some don't. Now the client is lenient, allowing the `Complete` message to be present or not, without throwing an exception in either case.
=> Stick with message decoder once type matches. Make "complete" messages optional.

.github/dependabot.yml, .github/workflows/release.yml, .github/workflows/scala.yml, MACROS.md, macros/src/main/scala/clue/macros/GraphQL.scala, macros/src/main/scala/clue/macros/GraphQLMacro.scala, macros/src/main/scala/clue/macros/GraphQLSchema.scala, macros/src/main/scala/clue/macros/Macro.scala, model/shared/src/main/scala/clue/data/Input.scala, model/shared/src/main/scala/clue/data/syntax/package.scala, model/shared/src/test/scala/clue/data/InputSpec.scala, model/shared/src/test/scala/clue/data/arb/ArbInput.scala, project/Settings.scala, project/build.properties
This is an attempt to deal with the fact that nullable input types actually can have 3 states:
* missing (undefined)
* `null` value
* actual value
We were previously modeling nullable input types as `Option[A]` but this fails short to model the fact that we can omit or send a `null` value to indicate "ignore" or "unset" semantics to a server.
A new 3-state sum type `Input[A]` was created with members `Undefined`, `Unset` and `Set(a)`. The macros now generate this type for nullable input values, with a default of `Undefined`.
Encoding is tricky and is a bit hackish: because of `circe`'s internal working, by the time we have to encode an `Input[A]` we are forced to provide a value. Therefore, a dummy value is provided for `Undefined`, which must be later on deep-wiped. Convenience methods …
=> Provide Undefined/Unset/Set options for input types.

core/shared/src/main/scala/clue/ApolloStreamingClient.scala, core/shared/src/main/scala/clue/ApolloWebSocketClient.scala, core/shared/src/main/scala/clue/GraphQLPersistentClient.scala, core/shared/src/main/scala/clue/GraphQLWebSocketClient.scala, core/shared/src/main/scala/clue/PersistentBackend.scala, core/shared/src/main/scala/clue/PersistentClient.scala, core/shared/src/main/scala/clue/WebSocketBackend.scala, core/shared/src/main/scala/clue/WebSocketReconnectionStrategy.scala, core/shared/src/main/scala/clue/package.scala, model/shared/src/main/scala/clue/model/StreamingMessage.scala, model/shared/src/main/scala/clue/model/json/package.scala, model/shared/src/test/scala/clue/model/arb/ArbFromClient.scala, model/shared/src/test/scala/clue/model/arb/ArbFromServer.scala, model/shared/src/test/scala/clue/model/arb/ArbJson.scala, scalajs/src/main/scala/clue/js/WebSocketJSBackend.scala
I was not convinced at all of the embedded types used in `0.5.0`. It resulted in an awkward API.
This PR works around the issue by moving `CloseParameters` and `CloseEvent` to client's and backend's type parameters, and creating convenience types for Web Socket instances.
Also, `ReconnectionStrategy` is now in the client instead of being passed in the `connect` method.
Also, uses of `JsonObject` in the `StreamingMessage`s were replaced by `Map[String, Json]`.
=> Type rework with Web Socket instances. ReconnectionStretegy in client.

core/shared/src/main/scala/clue/ApolloClient.scala, core/shared/src/main/scala/clue/ApolloWebSocketClient.scala, core/shared/src/main/scala/clue/PersistentClient.scala, core/shared/src/main/scala/clue/StreamingClientStatus.scala, core/shared/src/main/scala/clue/package.scala, scalajs/src/main/scala/clue/js/WebSocketJSBackend.scala
We now allow differentiating between underlying channel state (eg: web socket connected/disconnected) and protocol state (eg: apollo initialized/terminated).
This implied a nontrivial rework of the connection and disconnection logic.
Now, the client will request to `init` or `terminate` (instead of the former `connect`/`disconnect`). When `init` is called, the channel will be `connected` if it's not yet. When `terminate` is called, the client has the option to `KeepConnection` or `Disconnect`.
Furthermore, when the `reconnectionStrategy` function is invoked, now the client is informed whether an error occurred or a normal disconnection.
=> Disconnect rework.

core/shared/src/main/scala/clue/ApolloClient.scala, core/shared/src/main/scala/clue/ApolloWebSocketClient.scala, core/shared/src/main/scala/clue/StreamingClientStatus.scala, project/Settings.scala, scalajs/src/main/scala/clue/js/WebSocketJSBackend.scala
* Remove `Terminated` status. When a session is terminated but the channel is kept open, we should go straight to `Connected`.
* Added names for client, for easier logging. If not passed, the `uri` is used.
* When reconnecting, do not connect until after waiting. This is the right logic. It does introduce a bug though where messages sent by the client while waiting are queued up in the old, discarded client. Fixing this requires a larger change in the logic, which will be addressed in a future PR.
=> Fix reconnect logic. Add names for clients.

macros/src/main/scala/clue/macros/GraphQL.scala, macros/src/main/scala/clue/macros/GraphQLMacro.scala, macros/src/main/scala/clue/macros/GraphQLSchema.scala, macros/src/test/resources/graphql/schemas/LucumaODB.graphql, macros/src/test/resources/graphql/schemas/StarWars.graphql, macros/src/test/scala/clue/macros/MacroTest.scala, project/Settings.scala
Nullable fields for union types were not generating the corresponding sum type. A newer version of grackle now contemplates `UnionType` in `underlyingObject`, which simplifies our logic and correctly captures this case.
Also: Schema and test updates, throw an exception now when a type cannot be resolved (instead of generating a generic `Json` field).
=> Nullable fields with union types. Updates.

model/shared/src/main/scala/clue/data/Input.scala
For some reason I find my self expecting `Input.assign` but it doesn't exist.  Would it be okay to add it?
=> assign alias

core/shared/src/main/scala/clue/ApolloClient.scala, macros/src/test/scala/clue/macros/MacroTest.scala
Whenever an "error" message was received on a subscription, `clue` logged it. However, we may want to handle them at the application level, so these are not logged anymore (they still produce an error on the stream or effect).
Also, in case of errors on queries/mutations over persistent connections we were cleaning up the subscription queue twice. We now solve this by letting the "complete" message from the server trigger the cleanup.
=> Dont log handled errors

README.md, core/shared/src/main/scala/clue/ApolloClient.scala
* More info on errors.
* Avoid errors on edge cases when stopping subscriptions upon termination/disconnection, by either applying contention or contemplating these specific cases.
* Update documentation.
* Simplify obsolete code.
=> More info. Don't error on edge cases.

core/shared/src/main/scala/clue/ApolloClient.scala, core/shared/src/main/scala/clue/GraphQLException.scala, core/shared/src/main/scala/clue/TransactionalClientImpl.scala, model/shared/src/main/scala/clue/model/GraphQLError.scala, model/shared/src/main/scala/clue/model/json/package.scala, model/shared/src/test/scala/clue/model/arb/ArbGraphQLError.scala, model/shared/src/test/scala/clue/model/json/GraphQLErrorJsonSpec.scala
Working on testing for expected errors in GraphQL queries, I noticed that I could only extract the error information from the `GraphQLException` message `String`.  Wanting easier access to the actual errors, I added a `ResponseException` that keeps up with the `Json` array itself and support for turning this into structured data.
I'm not sure about or convinced of any of this so take it as a request to obtain access to error information somehow and let me know if there are better ways to accomplish this.
=> Add ResponseException and GraphQLErrors

MACROS.md, build.sbt, gen/input/src/main/scala/test/LucumaQuery.scala, gen/input/src/main/scala/test/LucumaQuery3.scala, gen/input/src/main/scala/test/StarWarsQuery.scala, gen/input/src/main/scala/test/StarWarsQuery2.scala, gen/output/src/main/scala/test/LucumaQuery.scala, gen/output/src/main/scala/test/LucumaQuery3.scala, gen/output/src/main/scala/test/StarWarsQuery.scala, gen/output/src/main/scala/test/StarWarsQuery2.scala, gen/rules/src/main/scala/clue/gen/Generator.scala, gen/rules/src/main/scala/clue/gen/QueryGen.scala, project/Settings.scala
Generating types for queries that return `|` or `interface` types no longer requires a discriminator. Instead, trial and error is used as described in https://circe.github.io/circe/codecs/adt.html.
This removes the need to depend on `circe-generic-extras` and therefore makes the generator work in Scala 3.
=> Generate decoder for sums without generic-extras.

core/src/main/scala/clue/ApolloClient.scala, core/src/main/scala/clue/TransactionalClientImpl.scala, core/src/main/scala/clue/package.scala
This fixes a couple issues I ran into while writing some tests for the new ODB:
- `emitError` was not extracting the error list correctly from the response when constructing a `ResponseException` which resulted in an empty list when calling `asGraphQLErrors`
- Errors returned by the GraphQL backend as a GraphQL response aren't really worth logging at a high level because we know they have been detected and handled by the back end. So I turned logging down for that case.
=> small changes in error handling

core/src/main/scala/clue/ApolloClient.scala
This PR will restore the previous `emitError` behavior in the `ApolloClient`.  I'll leave the line being changed commented out, since @tpolecat may want to look at this again.
=> Restore previous emitError behavior

build.sbt, http4s-jdk-demo/src/main/scala/clue/http4sjdkDemo/Demo.scala, http4s/src/main/scala/clue/http4s/Http4sBackend.scala, http4s/src/main/scala/clue/http4s/Http4sWSBackend.scala, project/Settings.scala
The http4s-jdk-client module now becomes an http4s module implemented purely in terms of the `Client` and `WSClient` interfaces which are shared between the http4s-jdk-http-client and http4s-dom.
=> Make http4s integration backend-agnostic

build.sbt, gen/rules/src/main/scala/clue/gen/Generator.scala
We added a new setting to sbt-typelevel so that you can safely compile an artifact for JDK 8 even if you are running in a newer JDK. So we can use that to publish for JDK 8 without changing CI.
Closes https://github.com/gemini-hlsw/clue/issues/326.
=> Use `tlJdkRelease` setting

core/src/main/scala/clue/ApolloClient.scala
It seems like it should be okay to ignore a `Complete` message from the server when already disconnected?
=> Switch to debug for Complete on Disconnected

core/src/main/scala/clue/BigNumberEncoders.scala
I had a problem with sending Long values to the new ODB based on Grackle. Apparently, when the Long value exceeds the size of a GraphQL integral type, Grackle falls back to treating it as a floating point. This caused a validation error because the API expected in integral value. The same thing could happen for BigInt and BigDecimal. The solution is to send these types quoted like strings. 
This currently requires a specific inclusion in the GraphGLSchema file, but I wonder if we should make these the default since the number sizes are part of the GraphQL spec?
=> Add quoting encoders for Long, BigInt and BigDecimal

core/src/main/scala/clue/GraphQLSubquery.scala
Convenient way to define subqueries for previously defined types with existing decoders.
=> GraphQLSubquery.Typed

build.sbt, core/src/main/scala/clue/ClientAppliedF.scala, core/src/main/scala/clue/FetchClientImpl.scala, core/src/main/scala/clue/GraphQLOperation.scala, core/src/main/scala/clue/clients.scala, core/src/main/scala/clue/package.scala, gen/output/src/main/scala/test/LucumaQuery.scala, gen/output/src/main/scala/test/LucumaQuery2.scala, gen/output/src/main/scala/test/LucumaQuery3.scala, gen/output/src/main/scala/test/StarWarsQuery.scala, gen/output/src/main/scala/test/StarWarsQuery2.scala, gen/output/src/main/scala/test/StarWarsQuery3.scala, gen/output/src/main/scala/test/StarWarsQuery4.scala, gen/rules/src/main/scala/clue/gen/QueryGen.scala, http4s-jdk-demo/src/main/scala/clue/http4sjdkDemo/Demo.scala, http4s/src/main/scala/clue/http4s/Http4sHttpClient.scala, http4s/src/main/scala/clue/http4s/package.scala, scalajs/src/main/scala/clue/js/package.scala
- In fetch requests, the common case is that we don't want to manipulate the underlying transport layer request (with type `P`). The old `FetchClient[F, P, S]` is therefore renamed to `FetchClientWithPars[F, P, S]` and a type alias is introduced `FetchClient[F, S]` for the common case.
- Introduce `GraphQLOperation.Typed[S, V, T]` and `GraphQLOperation.Typed.NoInput[S, T]` to easily define self-contained operations when there are implicit data decoders and variable encoders available.
- Demo was updated to use the changes.
=> Friendlier type params

build.sbt, core/src/main/scala/clue/ErrorPolicy.scala, core/src/main/scala/clue/GraphQLException.scala, model/src/main/scala/clue/model/json/package.scala
The `RaiseAlways` error policy raises an error if `errors` are present in the response. `data` can also be present, but it was discarded until now. Now it is included in the exception if present.
=> Include data (if present) in response exceptions

core/src/main/scala/clue/websocket/ApolloClient.scala, scalajs/src/main/scala/clue/js/FetchJSBackend.scala, scalajs/src/main/scala/clue/js/WebSocketJSBackend.scala
The new `async` cancelation semantics of `cats-effect` (see https://github.com/typelevel/cats-effect/releases/tag/v3.5.0) prompted a revision of the uses of `.async`, which led to this PR where we implment now proper handling of cancelation.
=> Better cancelation

build.sbt, core/src/main/scala/clue/ErrorPolicy.scala, core/src/main/scala/clue/FetchClientImpl.scala, core/src/main/scala/clue/websocket/ApolloClient.scala, http4s-jdk-demo/src/main/scala/clue/http4sjdkDemo/Demo.scala, model/src/main/scala/clue/model/GraphQLDataResponse.scala, model/src/main/scala/clue/model/GraphQLResponse.scala, model/src/main/scala/clue/model/StreamingMessage.scala, model/src/main/scala/clue/model/json/package.scala, model/src/main/scala/clue/model/package.scala, model/src/test/scala/clue/ListLimitingDisciplineSuite.scala, model/src/test/scala/clue/model/GraphQLResponseSpec.scala, model/src/test/scala/clue/model/arb/ArbFromServer.scala, model/src/test/scala/clue/model/arb/ArbGraphQLError.scala, model/src/test/scala/clue/model/arb/ArbGraphQLResponse.scala, model/src/test/scala/clue/model/json/GraphQLDataResponseJsonSpec.scala, model/src/test/scala/clue/model/json/GraphQLErrorJsonSpec.scala, model/src/test/scala/clue/model/json/GraphQLRequestJsonSpec.scala, model/src/test/scala/clue/model/json/StreamingMessageJsonSpec.scala
An exception was being raised when a `data: null` element was present in a response, which is valid. Also, response `extensions` were not propagated.
This PR fixes both issues by an internal refactor in the representation of the responses, now using `GraphQLResponse`.
=> Propagate response extensions, allow empty data

core/src/main/scala/clue/websocket/ApolloClient.scala
Single shot queries clean up after themselves when `stop` is received from the server. There's no need for actively cleaning up if the fiber is cancelled.
This resulted in `Invalid subscription id` errors if the fiber was cancelled right after the query ended.
=> Remove cancellation cleanup on single-shot queries over Apollo protocol

build.sbt, model/src/main/scala/clue/model/StreamingMessage.scala, model/src/main/scala/clue/model/json/package.scala, model/src/test/scala/clue/model/arb/ArbFromServer.scala
According to [spec](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_error), the payload of `ConnectionError` is an `Object`.
=> Fix ConnectionError payload type

build.sbt, core/src/main/scala/clue/GraphQLException.scala, core/src/main/scala/clue/clients.scala, core/src/main/scala/clue/package.scala, core/src/main/scala/clue/websocket/ApolloClient.scala, scalajs/src/main/scala/clue/js/WebSocketJSBackend.scala
- More specific exceptions to allow better handling.
- Propagate main fiber cancelation across async boundaries (connect and initialize latches).
- Effectful payload for initialization. Allows getting updated values when retry mechanism kicks in.
- Downgrade some detailed log messages from debug to trace.
=> Specific exceptions, async cancel propagation, effectful init payload

build.sbt, core/src/main/scala/clue/PersistentClientStatus.scala, core/src/main/scala/clue/clients.scala, core/src/main/scala/clue/package.scala, core/src/main/scala/clue/websocket/ApolloClient.scala, core/src/main/scala/clue/websocket/Emitter.scala, core/src/main/scala/clue/websocket/State.scala, http4s-jdk-demo/src/main/resources/simplelogger.properties, http4s-jdk-demo/src/main/scala/clue/http4sjdkDemo/Demo.scala
A connected but uninitialized client is of no use for any API client. Therefore, this PR unifies both operations into one (retriable) operation.
This dramatically simplifies the internals of the client, making it simpler to maintain and detect bugs.
In particular, I think this finally fixes some issues with the retry logic.
=> Unify connect and initialize operations into one

build.sbt, core/src/main/scala/clue/FetchClientImpl.scala, core/src/main/scala/clue/clients.scala, core/src/main/scala/clue/websocket/ApolloClient.scala, http4s-jdk-demo/src/main/scala/clue/http4sjdkDemo/Demo.scala, model/src/main/scala/clue/model/GraphQLResponse.scala
Avoids having to explicitly call `apply` when we have a query or subscription without input variables and we want to apply the new extension methods.
Also, update Demo. It now works again.
=> Improve ergonomics

gen/rules/src/main/scala/clue/gen/package.scala
This matches what was already done in the ODB and is required to parse the bigger input objects in the odb queries.
=> Increase maxInputValueDepth for grackle parser

core/src/main/scala/clue/clients.scala, core/src/main/scala/clue/websocket/ApolloClient.scala, core/src/main/scala/clue/websocket/State.scala, model/src/main/scala/clue/model/StreamingMessage.scala, model/src/main/scala/clue/model/json/package.scala, model/src/main/scala/clue/model/package.scala, model/src/test/scala/clue/model/arb/ArbFromClient.scala, model/src/test/scala/clue/model/arb/ArbFromServer.scala, model/src/test/scala/clue/model/arb/ArbJson.scala
This might be a good time to make this other breaking change. I find it's cleaner to pass JsonObjects around than Map[String, Json], and it saves an encoding/decoding step.
=> Change Maps to JsonObject

build.sbt, gen/input/src/main/resources/graphql/schemas/LucumaODB.graphql, gen/input/src/main/resources/graphql/schemas/StarWars.graphql, gen/output/src/main/scala/test/LucumaODBSchema.scala, gen/output/src/main/scala/test/StarWarsQuery.scala, gen/output/src/main/scala/test/StarWarsQuery2.scala, gen/output/src/main/scala/test/StarWarsQuery3.scala, gen/rules/src/main/scala/clue/gen/Generator.scala, gen/rules/src/main/scala/clue/gen/QueryGen.scala, gen/rules/src/main/scala/clue/gen/SchemaGen.scala
- Propagate deprecated directives as annotations in generated code.
- Emit warning if a deprecated field is referenced in a query.
=> Handle deprecations

build.sbt, gen/rules/src/main/scala/clue/gen/GraphQLGen.scala, gen/rules/src/main/scala/clue/gen/QueryGen.scala
This PR will check that:
- Arguments to queries and fields are declared in the schema.
- Check their type is compatible.
- All required arguments without default values are declared.
This is a revised edition of https://github.com/gemini-hlsw/clue/pull/722 which recurses into objects and lists, and uses simpler logic by co-opting grackle's variable resolver.
=> Validate query arguments - Take 2
